development:
  bucket_name: dev.lamestuff.com
  access_key_id: 'XXXXXXXXXXXX'
  secret_access_key: 'XXXXXXXXXXXX'

test:
  bucket_name: test.lamestuff.com
  access_key_id: 'XXXXXXXXXXXX'
  secret_access_key: 'XXXXXXXXXXXX'

production:
  bucket_name: lamestuff.com
  access_key_id: 'XXXXXXXXXXXX'
  secret_access_key: 'XXXXXXXXXXXX'

staging:
  bucket_name: lamestuff.com
  access_key_id: 'XXXXXXXXXXXX'
  secret_access_key: 'XXXXXXXXXXXX'
